### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Nzrall** [learn-co-curriculum/phase-3-active-record-mechanics#3]
### Canvas Link

https://learning.flatironschool.com/courses/4543/pages/active-record-mechanics?module_item_id=335989

### Concern

line 82 of the README.md has a link to Class inheritance @ rubylearning.com that is broken, figured I would let you know.

### Suggested Changes

See whether or not the link is functioning properly and directs you to correct material you want students to read

**Comment by lizbur10** [comment]
Hi @Nzrall ! Thanks for bring this to our attention! 

I'm going to leave this issue open for now, in case the problem with the destination site is temporary and resolves itself.

**Comment by lizbur10** [comment]
Hi @Nzrall ! Thanks again for flagging this. The broken link has been replaced. Note that you may not see the change reflected in your Canvas course right away, but it will be present going forward.

Thanks for contributing to the Flatiron School curriculum 💙
